# -*- coding: utf-8 -*-
"""Twitter Sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vt0NgfjQETpXnJ_OEOXfpcyFzJENmPOO
"""

!pip install kaggle

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d kazanova/sentiment140

from zipfile import ZipFile
dataset = '/content/sentiment140.zip'

with ZipFile(dataset, 'r') as zip:
  zip.extractall()
  print('The dataset is extracted')

import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

import nltk
nltk.download('stopwords')

print(stopwords.words('english'))

twitter_data = pd.read_csv('/content/training.1600000.processed.noemoticon.csv', encoding = 'ISO-8859-1')

twitter_data.shape

twitter_data.head()

column_names = ['target', 'ids', 'date', 'flag', 'user', 'text']
twitter_data = pd.read_csv('/content/training.1600000.processed.noemoticon.csv',names=column_names ,encoding  = 'ISO-8859-1')

twitter_data.shape

twitter_data.head()

twitter_data. isnull().sum()

twitter_data['target'].value_counts()

twitter_data.replace({'target':{4:1}}, inplace=True)

twitter_data['target'].value_counts()

"""Stemming"""

port_stemmer = PorterStemmer()

port_stemmer = PorterStemmer()

def stemming(contant):
    # Remove non-alphanumeric characters and convert to lowercase
    stemmed_content = re.sub('[^a-zA-Z]', '', contant)
    stemmed_content = stemmed_content.lower()
    # Split the content into words
    stemmed_content = stemmed_content.split()
    # Get list of English stopwords from NLTK
    english_stopwords = stopwords.words('english')
    # Apply stemming to each word if it's not a stopword
    stemmed_content = [port_stemmer.stem(word) for word in stemmed_content if not word in english_stopwords]
    # Join the stemmed words back into a string
    stemmed_content = ' '.join(stemmed_content)

    return stemmed_content

twitter_data['stemmed_content'] = twitter_data['text'].apply(stemming)

twitter_data.head()

print(twitter_data['stemmed_content'])

print(twitter_data['target'])

X=twitter_data['stemmed_content'].values
Y=twitter_data['target'].values

print(X)

print(Y)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size =0.2, stratify=Y, random_state=2  )

print(X.shape, x_train.shape, X_test.shape)

print(X_train)

print(X_test)

vectorizer = TfidfVectorizer()

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

print(X_train)

print(X_test)

model = LogisticRegression(max_iter=1000)

model.fit(X_train,Y_train)

X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)

print('Accuracy score on the training data : ', training_data_accuracy)

X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(Y_test, X_test_prediction)

print('Accuracy score on the training data : ', test_data_accuracy)

import pickle

filename='trained_model.sav'
pickle.dump(model,open(filename,'wb'))

loaded_model=pickle.load(open('/content/trained_model.sav','rb'))

X_new = X_test[200]

print(Y_test[200])
prediction = loaded_model.predict(X_new)
print(prediction)

if (prediction[0] ==0):
  print('Negative Tweet')

else:
  print('Positive Tweet')

X_new = X_test[2]
print(Y_test[2])
prediction = loaded_model.predict(X_new)
print(prediction)

if (prediction[0] ==0):
  print('Negative Tweet')

else:
  print('Positive Tweet')